# Generated by Django 5.2.1 on 2025-05-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='is_completed',
            new_name='isCompleted',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='is_recurring',
            new_name='isRecurring',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='updated_at',
            new_name='lastSynced',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='recurring_pattern',
            new_name='recurringPattern',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='scheduled_date',
            new_name='scheduledDate',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
